### PR TITLE
Update AllergyIntolerance and Condition Note

### PR DESCRIPTION
**Pull request by averyallen**
Adds notes to AllergyIntolerance.note and Condition.notes.

### CODE REVIEW

**Comment by ericsornson** [comment]
+1

**Comment by daliboz** [comment]
Instead of adding it in the body fields (since it already has note.x fields, and they may completely skip that), how about adding it to the Notes section just above the body fields table?

**Comment by averyallen** [comment]
@daliboz, moved to the Notes section above the field tables:  0a2f360

**Comment by daliboz** [comment]
+1

**Pull request merged**
