### PR TITLE
R4 DocumentsReference Read and Search examples are updated

### PR DESCRIPTION
**Pull request by akashdeep677**
Description
----

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

Screenshot 2022-08-10 at 12 27 19 PM

### CODE REVIEW

**Comment by akashdeep677** [comment]
example search by patient (patient persona)
example serach with encounter
example serach by patient with rev_include
example_search_by_patient
example-_read_by_id_patient_persona
example_read_by_id

**Review by aki-mathur — APPROVED** [review]

**Comment by akashdeep677** [comment]
Screenshot 2022-07-20 at 1 15 32 PM
Screenshot 2022-07-20 at 1 15 15 PM
Screenshot 2022-07-20 at 1 15 05 PM

**Review by jj027509 — APPROVED** [review]

**Comment by akashdeep677** [comment]
Screenshot 2022-09-30 at 3 21 12 PM

**Review by Surya-Rnsit — APPROVED** [review]

**Comment by NimishaMN** [comment]
Changes merged and published
Screenshot 2022-10-13 at 3 15 12 PM
Screenshot 2022-10-13 at 3 15 36 PM
Screenshot 2022-10-13 at 3 15 55 PM
Screenshot 2022-10-13 at 3 16 20 PM

**Pull request merged**
