### PR TITLE
Update R4 Location example URLs

### PR DESCRIPTION
**Pull request by MaxPhilips**
Description
----
Fix a couple Location example URLs

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Comment by MaxPhilips** [comment]
pre-merge verification
Screen Shot 2021-01-22 at 3 57 45 PM

**Review by DanielWhiteCerner — APPROVED** [review]

**Review by sydneanschutz — APPROVED** [review]

**Comment by MaxPhilips** [comment]
i'm going to make the example on the page itself make the example in the json

**Comment by MaxPhilips** [comment]
new pre-merge verification
Screen Shot 2021-01-25 at 1 58 55 PM

**Review by DanielWhiteCerner — APPROVED** [review]

**Review by sydneanschutz — APPROVED** [review]

**Comment by MaxPhilips** [comment]
post-merge verification
Screen Shot 2021-02-01 at 4 38 08 PM

**Pull request merged**
