### PR TITLE
Patient extension links

### PR DESCRIPTION
**Pull request by jogden18**
Description
----
Updated link addresses for patient extensions

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Review by lalitha94 — APPROVED** [review]

**Review by maruthiallam — APPROVED** [review]

**Comment by joeratt** [comment]
CC: @kathypickering

**Review by joeratt — APPROVED** [review]
All links are valid now, including extensions

**Review by kathypickering — APPROVED** [review]

**Comment by Mohammad-Isyroqi-Fathan** [comment]
Screenshots before merged

Screen Shot 2021-07-09 at 2 31 03 PM

**Comment by Mohammad-Isyroqi-Fathan** [comment]
Screenshots after merged

Screen Shot 2021-07-09 at 2 29 54 PM

**Pull request merged**
