### PR TITLE
Update document-reference.md with plain and richtext Mime types

### PR DESCRIPTION
**Pull request by Lisper50**
DocumentReference add Mime types text/plain and text/richtext

Description
----
Add supported Mime types to content.attachment.content_type
PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Review by HunterBerten — APPROVED** [review]

**Review by mayur-rajendran — COMMENTED** [review]
Can we also get the allowed values added here: https://github.com/cerner/fhir.cerner.com/blob/main/lib/resources/r4/document_reference.yaml#L197

**Review by mayur-rajendran — APPROVED** [review]

**Comment by Lisper50** [comment]
Before change screen shot:
Production with out changes 2020-09-24

Running change locally screen shot:
Planed change contentType  2020-09-24

**Comment by Lisper50** [comment]
**Supported Mime type running local (with change):**  
Local - Supported 2020-09-24

**Supported Mime type Orginal:**
Original - Supported 2020-09-24

**Comment by MaxPhilips** [comment]
verified on live

Screen Shot 2020-09-24 at 6 00 47 PM

**Pull request merged**
