### PR TITLE
R4 Encoding Narrative Characters to Valid XHTML

### PR DESCRIPTION
**Pull request by ShrutiNHegde**
Description
----
https://jira2.cerner.com/browse/OPENSVC-20482
https://jira2.cerner.com/browse/OPENSVC-21357

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

Schedule Resource:
Schedule_Resource

Procedure Resource:
Procedure_resource

CarePlan Resource:
CarePlan

Allergy Intolerance:
AllergyInterolance

### CODE REVIEW

**Review by NimishaMN — APPROVED** [review]
LGTM

**Review by gokul-cerner — COMMENTED** [review]
Is there a resource(s) that we're missing? In "R4 Encoding narrative characters to valid xhtml," the common file has been modified.

**Comment by ShrutiNHegde** [comment]
I have verified other resource(s). It is not including the invalid characters. I have modified the resource which includes the invalid characters in the example.

**Review by gokul-cerner — APPROVED** [review]

**Comment by zxeleven** [comment]
Verified live:

Screen Shot 2021-08-05 at 4 40 39 PM
Screen Shot 2021-08-05 at 4 41 30 PM
Screen Shot 2021-08-05 at 4 43 28 PM
Screen Shot 2021-08-05 at 4 44 46 PM

**Pull request merged**
