### PR TITLE
Fixed minor typo/word choice and corrected small inaccuracy around redirect URIs

### PR DESCRIPTION
**Pull request by weeznerps**
Support for multiple redirect URIs was recently introduced

### CODE REVIEW

**Comment by daliboz** [comment]
+1, @kolkheang @mjhenkes Thoughts on pushing this before code console changes?

**Comment by kolkheang** [comment]
@daliboz - I think we should hold off pushing the documentation for multiple redirect support until we have the functionality in code Console.  At this point, we don't know when we will get to implement this functionality (probably end of Q4).

**Comment by daliboz** [comment]
@kolkheang @mjhenkes with the clarification coming from #186, good with pushing this in now?

**Comment by kolkheang** [comment]
@daliboz  - yes, I think this is fine.

**Pull request merged**
