### PR TITLE
Update Observation example to reflect flattened social history structure

### PR DESCRIPTION
**Pull request by MaxPhilips**
The intermediary 'form' social history is no longer displayed, and the value of the social history is its assessment.

### CODE REVIEW

**Comment by daliboz** [comment]
+1 unless we can also add one of the results that's just assessment?

**Comment by MaxPhilips** [comment]
I forgot that there was actually an assessment-only result already included.  I updated its id to include the 'a' it is now rendered with: 92f18b1

**Comment by daliboz** [comment]
+1

**Comment by MadhurRaj** [comment]
+1

**Pull request merged**
