### PR TITLE
R4 - Update procedure resources

### PR DESCRIPTION
**Pull request by napster235**
Description
----
Add supported references to procedure

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Comment by napster235** [comment]
Before
Screenshot 2022-08-31 at 14 40 44
After commit 5d7afdb
Screenshot 2022-08-31 at 15 28 55

**Comment by napster235** [comment]
After commit d0ece28
Screenshot 2022-09-01 at 14 48 17

**Comment by napster235** [comment]
After 747e1a4
Screenshot 2022-09-01 at 15 28 47

**Comment by MariaPislaru1** [comment]
@napster235 fyi

**Review by lstefan4 — APPROVED** [review]

**Review by cerbs — CHANGES_REQUESTED** [review]

**Comment by napster235** [comment]
After code review changes in commit 8e8d0de
Screenshot 2022-09-07 at 15 28 22

**Review by davischristi — APPROVED** [review]
Looks good.

**Review by cerbs — APPROVED** [review]

**Pull request merged**
