### PR TITLE
Fix the terminology binding for MedicationOrder.dosageInstruction.rou…

### PR DESCRIPTION
**Pull request by jfrhong**
…te and MedicationStatement.dosage.route

### CODE REVIEW

**Comment by JFisk42** [comment]
+1

**Comment by daliboz** [comment]
+1, but let's hold for confirmation that we'll continue excluding SNOMED for the immediate future

(documenting offline conversation)

**Comment by daliboz** [comment]
@jfrhong per the jira, instead of replacing snomed, leave both.

**Comment by jfrhong** [comment]
@JFisk42 @daliboz can you guys take a look again? Added NCI instead of removing SNOMED and also updated Immunization

**Comment by daliboz** [comment]
+1

**Comment by JFisk42** [comment]
+1

**Pull request merged**
