### PR TITLE
Updated patient to true in authorization_types for Organization

### PR DESCRIPTION
**Pull request by Zonglin123**
Description
----
Updated the Organization.md and changed the patient from false to true in authorization_types.
Screen Shot 2020-08-20 at 2 20 06 PM
Screen Shot 2020-08-20 at 2 20 34 PM

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Comment by sonikrish** [comment]
Can you add the Resource name in the heading so that we know which resource we are talking about.

**Comment by sonikrish** [comment]
Also, some description for the fields which is filtered for patient access like this https://github.com/cerner/fhir.cerner.com/pull/447/files

**Review by sonikrish — APPROVED** [review]

**Comment by Zonglin123** [comment]
> Don't reference the Jira number in this PR.
> See: https://wiki.cerner.com/display/Open/Contributing+to+fhir.cerner.com

Updated on heading and commit message.
https://github.com/cerner/fhir.cerner.com/pull/449/commits

**Comment by ebbp123** [comment]
Verified Live:
Screen Shot 2020-08-27 at 3 44 04 PM
Screen Shot 2020-08-27 at 3 44 13 PM

**Pull request merged**
