### PR TITLE
Documentation for Person combines

### PR DESCRIPTION
**Pull request by cerbs**
Updating the Person resource to address upcoming person combine behavior similar to the Patient resource.

### CODE REVIEW

**Comment by ericsornson** [comment]
Millennium uses the term `combine`, but FHIR refers to it as `merging`.

Should we be using the term `merging` in this documentation except where we refer to the millennium operation?  Might be worth calling out that distinction here as well.

**Comment by cerbs** [comment]
I would prefer to stay with "combine" to be consistent with the existing Patient resource documentation. This is also describing how a Millennium "combine" is reflected through our API.

**Comment by beichhor** [comment]
+1

**Comment by averyallen** [comment]
+1

**Pull request merged**
