### PR TITLE
Fix links to code.cerner.com

### PR DESCRIPTION
**Pull request by daliboz**
Fix links to code.cerner.com, minor fix to SMART FAQ to remove kramdown warning.

All links that went to the ehr-api locations should now go to millennium on code.cerner.com

### CODE REVIEW

**Comment by daliboz** [comment]
@kolkheang If you want to sanity check the tiny change on the smart faq... (it was producing a kramdown warning since it wasn't in code blocks or escaped)

**Comment by kolkheang** [comment]
+1
@daliboz - thanks for fixing this!  Yeah, that makes sense.  I forgot to add the `` around `<head>`.

**Comment by MaxPhilips** [comment]
+1

**Comment by daliboz** [comment]
@kolkheang would you like be to put it in the single quote? Right now I just escaped the beginning of the tag.

**Comment by kolkheang** [comment]
@daliboz - I think it's fine as it is now.

**Pull request merged**
