### PR TITLE
 replace create with write for ChargeItem 

### PR DESCRIPTION
**Pull request by krvicky31**
Description
----
Change fhir.cerner.com for ChargeItem Create to ChargeItem Write

Related Pr
----
https://github.com/cerner/fhir.cerner.com/pull/778

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
Screenshot 2021-12-28 at 3 37 32 PM
Screenshot 2021-12-28 at 3 37 49 PM
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Comment by krvicky31** [comment]
@alexbeckner1 Url change is also required? here https://github.com/cerner/fhir.cerner.com/pull/778/files#diff-03f941e4ceb2839bfe0b49a5cc913e04919560e289603ae7b08b875f86ec568dR298.

**Review by Nandita92 — APPROVED** [review]

**Comment by alexbeckner1** [comment]
> @alexbeckner1 Url change is also required? here https://github.com/cerner/fhir.cerner.com/pull/778/files#diff-03f941e4ceb2839bfe0b49a5cc913e04919560e289603ae7b08b875f86ec568dR298.

Yes. We should update the example request and response location with write

**Comment by krvicky31** [comment]
> > @alexbeckner1 Url change is also required? here https://github.com/cerner/fhir.cerner.com/pull/778/files#diff-03f941e4ceb2839bfe0b49a5cc913e04919560e289603ae7b08b875f86ec568dR298.
> 
> Yes. We should update the example request and response location with write

So before updating the url here, We have to change the request url with write (changes in routes.rb and fts in tephra) so it can be routed to a proper page.

**Comment by alexbeckner1** [comment]
> > > @alexbeckner1 Url change is also required? here https://github.com/cerner/fhir.cerner.com/pull/778/files#diff-03f941e4ceb2839bfe0b49a5cc913e04919560e289603ae7b08b875f86ec568dR298.
> > 
> > 
> > Yes. We should update the example request and response location with write
> 
> So before updating the url here, We have to change the request url with write (changes in routes.rb and fts in tephra) so it can be routed to a proper page.

Is someone making that url change, or does a JIRA need to get logged to make that change? Would it be easier to just keep it all as create and revert the fhir.cerner.com changes and update the operation definition? cc @SantanuBanerjee and @exopsRamba

**Comment by krvicky31** [comment]
NA

**Pull request closed without merging**
