### PR TITLE
Reorganize R4 Resources, Add Overview Links, & Resolve Merge Conflicts

### PR DESCRIPTION
**Pull request by sa087145**
The goal of this PR is the same as beichhor's [Reorganize R4 Resources, Add Overview Links](https://github.com/cerner/fhir.cerner.com/pull/620). The description from this PR is copied and pasted below. 

_The changes in this PR are to accomplish two primary goals:
a) Organize the fhir.cerner.com resources for R4 to make sense and match how they are organized via the FHIR spec
b) Have the Overview table contain links automatically to the resources. The existing resource list in this PR was automatically generated from scraping the HL7 Resource list site https://www.hl7.org/fhir/r4/resourcelist.html The "Basic" resource link was removed (because it currently only links to FinancialTransaction but this helps avoid confusion) and the FinancialTransaction resource was added manually._

This new pull request has been created because Ben's came before a handful of other changes to fhir.cerner.com. This PR has resolved any merge conflicts.

Current running fhir.cerner.com screenshots:
[Old_MillenniumOverview.pdf](https://github.com/cerner/fhir.cerner.com/files/6648844/Old_MillenniumOverview.pdf)
[Old_R4MillenniumOverview.pdf](https://github.com/cerner/fhir.cerner.com/files/6648846/Old_R4MillenniumOverview.pdf)

Screenshots of changes made to site, running on localhost:
[MillenniumOverview.pdf](https://github.com/cerner/fhir.cerner.com/files/6648847/MillenniumOverview.pdf)
[R4MilleniumOverview.pdf](https://github.com/cerner/fhir.cerner.com/files/6648848/R4MilleniumOverview.pdf)

[JIRA](https://jira2.cerner.com/browse/OPENENGAGE-3647) for pull request.

----
PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Comment by Zonglin123** [comment]
Why there are two Provenances under the Security?
WeChatbd426f19c1f2d139a037de8b8e9c9d18

**Comment by ebbp123** [comment]
This looks good to me. I will approve once the conflicts have been fixed.

**Comment by sa087145** [comment]
> Why there are two Provenances under the Security?
> WeChatbd426f19c1f2d139a037de8b8e9c9d18

This was a mistake. I have committed and pushed changes to delete the second Security tab. According to https://www.hl7.org/fhir/r4/resourcelist.html, Security should be a subcategory of Foundation. Thank you!

**Review by ebbp123 — APPROVED** [review]
Looks good to me.

**Review by Zonglin123 — APPROVED** [review]
+1 after fixing the conflicting files.

**Pull request merged**
