### PR TITLE
Use FHIR parameter types and link to FHIR documentation.

### PR DESCRIPTION
**Pull request by dennispatterson**
Updated search parameter types across all existing pages to directly reflect FHIR types.  Also, removed 'name' from Observation DSTU 1 search parameters.

### CODE REVIEW

**Comment by dennispatterson** [comment]
Formatted the search parameter table markdown.

**Comment by MaxPhilips** [comment]
+1

**Comment by naveenaluru** [comment]
:+1:

**Comment by jfrhong** [comment]
+1

**Comment by dennispatterson** [comment]
Squashed and rebased .  Still need another +1.

@daliboz 
@kpshek

**Comment by daliboz** [comment]
+1

**Pull request merged**
