### PR TITLE
Update eTLD+1 documentation in application registration prerequisites

### PR DESCRIPTION
**Pull request by brailsmt**
Description
----
Update the eTLD+1 documentation in application registration prerequisites.

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

Screen Shot 2022-05-13 at 2 24 20 PM

### CODE REVIEW

**Comment by scott-bach** [comment]
+1 these changes look good to me.

**Comment by brailsmt** [comment]
Before:
Screen Shot 2022-05-13 at 14 21 37

After:
Screen Shot 2022-05-13 at 14 22 26

**Review by mbeerman — APPROVED** [review]

**Review by scott-bach — APPROVED** [review]
Changes look good.

**Comment by MadhurRaj** [comment]
published changes:
Screen Shot 2022-05-18 at 12 18 00 PM

**Pull request merged**
