### PR TITLE
Update confidential client doc

### PR DESCRIPTION
**Pull request by icon5585**
Description
----

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Comment by icon5585** [comment]
Only updated the FAQ around confidential clients coming in the future

**Review by daliboz — APPROVED** [review]
👍

**Review by jfrhong — APPROVED** [review]

**Comment by MaxPhilips** [comment]
no pre-merge SS attached since this is a trivial change

**Comment by nishanthnamana** [comment]
Validation from live site:
Screen Shot 2020-12-03 at 4 28 17 PM

**Pull request merged**
