### PR TITLE
Updating README.md with terminology_table documentation

### PR DESCRIPTION
**Pull request by cerbs**
Updating the README to include documentation on the terminology_table helper method

### CODE REVIEW

**Comment by MaxPhilips** [comment]
Want to drop the may2015 definition table example as part of this since we no longer have may2015 on the site?

+1

**Comment by cerbs** [comment]
It was there at the time! Rebased and made the working a little more generic

**Comment by MaxPhilips** [comment]
+1 for d1e8c8f

**Comment by JFisk42** [comment]
+1

**Pull request merged**
