### PR TITLE
R4 -  CarePlan Resource Updates

### PR DESCRIPTION
**Pull request by napster235**
Description
CarePlan resource needed an update so Author will contain a reference to practitioner

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Comment by napster235** [comment]
Before change
Screenshot 2022-08-29 at 18 31 50
After change
Screenshot 2022-08-30 at 10 19 20

**Comment by napster235** [comment]
Before typo change:
Screenshot 2022-08-30 at 10 27 34
Afte typo change in commit [24c171e]:
Screenshot 2022-08-30 at 10 34 20

**Review by learclite — APPROVED** [review]

**Comment by napster235** [comment]
After commit 981b118
Screenshot 2022-09-01 at 15 45 38

**Comment by MariaPislaru1** [comment]
@napster235 fyi

**Review by lstefan4 — APPROVED** [review]

**Review by davischristi — APPROVED** [review]

**Pull request merged**
