### PR TITLE
Upgrading to Nanoc 4 (and ruby 2.3.1)

### PR DESCRIPTION
**Pull request by daliboz**
I will leave the step-by-step commits in, following these directions: http://nanoc.ws/doc/nanoc-4-upgrade-guide/

You can generate an output.diff locally by:

1. clean the output directory
2. checkout master (may need to change ruby version)
3. bundle install
4. run nanoc
5. checkout nanoc4 (may need to change ruby version)
6. bundle install
7. run nanoc

Known diff: the may version will now have 3 levels of TOC, for consistency

### CODE REVIEW

**Comment by MaxPhilips** [comment]
The output.diff file I generated has lots of changes, looks like the nanoc4 branch needs to be rebased on master

**Comment by daliboz** [comment]
Weird. Something is messed up with my local because it's showing no changes even after fetch all... Will try wiping and starting again.

**Comment by daliboz** [comment]
Ok, should be fixed. My local master somehow lost it's remote association.

**Comment by MaxPhilips** [comment]
Should we add output.diff to .gitignore?

**Comment by MaxPhilips** [comment]
+1

**Comment by dennispatterson** [comment]
+1

**Pull request merged**
