### PR TITLE
R4 Appointment updates

### PR DESCRIPTION
**Pull request by amcginn**
Description
----
Update the R4 Appointment resource for consistency and readability.

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

Changes
----
Overview
before:
Screenshot 2023-09-22 at 13-00-34 Appointment R4 API

after:
Screenshot 2023-09-22 at 13-01-10 Appointment R4 API

Fields
before:
Screenshot 2023-09-22 at 13-17-46 Appointment R4 API

after:
Screenshot 2023-09-22 at 13-18-20 Appointment R4 API
**disclaimer and errors sentence were moved here and removed from each example**

Search parameters
before:
Screenshot 2023-09-22 at 13-23-50 Appointment R4 API

after (reordered, put field names as code, updated examples):
Screenshot 2023-09-22 at 13-24-47 Appointment R4 API

Search notes
before:
Screenshot 2023-09-22 at 13-37-37 Appointment R4 API

after:
Screenshot 2023-09-22 at 13-37-50 Appointment R4 API

Patch status
before:
Screenshot 2023-09-22 at 14-10-48 Appointment R4 API

after:
Screenshot 2023-09-22 at 14-17-22 Appointment R4 API

Patch video visit fields (common change on all fields)
before:
Screenshot 2023-09-22 at 14-23-54 Appointment R4 API

after:
Screenshot 2023-09-22 at 14-24-21 Appointment R4 API

### CODE REVIEW

**Review by kckeim — APPROVED** [review]
I'm annoyed on your behalf, @amcginn, that you had to correct so much poor grammar.
You caught all the ones that rubbed me the wrong way, and then some - it makes a lot more sense now.
Looks like you caught all the bad links too.

I'm marking as approved, but I do have a couple points of commentary to make sure we're being consistent with what our pages are supposed to look like (at least going forward).

***********************************

I don't know if we want to keep the disclaimer following all responses as a self-protective step, or switch to what you did with the one disclaimer section towards the top.  It certainly cuts down on the extra page space, but all of our other pages seems to have the disclaimers on there repeatedly.  Do you want to make a call either way, or decide as a group, so we can be consistent?

***********************************
Do we want to call out the specific read / write scopes that are referenced in the PATCH section's Implementation notes on line 179 of your corrected appointment.md file?  
This'd be something like `Appointment.read` and `Appointment.create` unless we want to keep the scopes non-specific  - what's your opinion here?

image

**Review by RicardoCrespo-ora — APPROVED** [review]

**Comment by amcginn** [comment]
> I don't know if we want to keep the disclaimer following all responses as a self-protective step, or switch to what you did with the one disclaimer section towards the top. It certainly cuts down on the extra page space, but all of our other pages seems to have the disclaimers on there repeatedly. Do you want to make a call either way, or decide as a group, so we can be consistent?

I thought we talked about this in scrum on the 22nd before I was out. Though, now I'm not sure you were there. It may have just been a missed communication on my part.
 
> Do we want to call out the specific read / write scopes that are referenced in the PATCH section's Implementation notes on line 179 of your corrected appointment.md file? This'd be something like `Appointment.read` and `Appointment.create` unless we want to keep the scopes non-specific - what's your opinion here?

I like that. We should be definitely be specific where it's easy to do so.

**Comment by amcginn** [comment]
Updated to specify scopes explicitly.

Screenshot 2023-10-03 at 14-33-23 Appointment R4 API

**Comment by Surya-Rnsit** [comment]
After Code Deployment: 
Screenshot 2023-11-10 at 3 44 51 PM
Screenshot 2023-11-10 at 3 44 30 PM

**Pull request merged**
