### PR TITLE
R4 Location Read Sweden Alias

### PR DESCRIPTION
**Pull request by olehepam**
- add identifiers

Description
----

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Comment by olehepam** [comment]
image

**Comment by olehepam** [comment]
image

**Comment by olehepam** [comment]
image

**Comment by olehepam** [comment]
image

**Review by Sanvenky — APPROVED** [review]

**Review by NeethuKP — APPROVED** [review]

**Comment by NeethuKP** [comment]
Looks like there are lint issues , can this be cross verified

**Comment by aki-mathur** [comment]
Closing this PR as we have new PR for this change https://github.com/cerner/fhir.cerner.com/pull/826

**Pull request closed without merging**
