### PR TITLE
Add information about scheme flooding

### PR DESCRIPTION
**Pull request by mbeerman**
Description
----
Microsoft Edge added new security measures in March 2022 that can be problematic for developers of native SMART applications; document what we know about the causes and resolutions.

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

Screen Shot 2022-08-22 at 12 49 35 PM

### CODE REVIEW

**Review by whitehatguy — APPROVED** [review]
+1

**Comment by scott-bach** [comment]
Can you add the cause or conditions in which they would need to have these settings required or, if they are always required, let them know that also?

**Review by scott-bach — APPROVED** [review]
Looks good with the update to include the error they might be seeing.

**Comment by aki-mathur** [comment]
Screenshot 2022-08-26 at 12 48 39 PM

**Pull request merged**
