### PR TITLE
Update documentation about contained resources in MedicationOrder and…

### PR DESCRIPTION
**Pull request by jfrhong**
… MedicationStatement.

### CODE REVIEW

**Comment by daliboz** [comment]
Clarify that we used contained when dealing with either multiple ingredient or compounded medications? The statement about them only existing within the context is confusing since we don't *always* use contained. IE: it's the concentrations/dilutions that typically cause it to be order specific.

**Comment by cerbs** [comment]
+1

**Comment by davischristi** [comment]
👍

**Comment by jfrhong** [comment]
@daliboz how about "MedicationStatement.medication may be a reference to a contained Medication when the Medication cannot be represented by a CodeableConcept because it contains a unique combination of ingredients."

**Comment by daliboz** [comment]
+1

**Pull request merged**
