### PR TITLE
OPENSVC-20966: Update fhir.cerner.com R4 Account Identifier search system url

### PR DESCRIPTION
**Pull request by gokul-cerner**
Description
----

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Comment by gokul-cerner** [comment]
Before merge the changes:
Screenshot 2021-07-13 at 4 39 54 PM
Screenshot 2021-07-13 at 4 40 19 PM
Screenshot 2021-07-13 at 4 40 40 PM

**Comment by gokul-cerner** [comment]
Before merge the changes:
Screenshot 2021-07-13 at 5 46 02 PM
Screenshot 2021-07-13 at 5 47 05 PM
Screenshot 2021-07-13 at 5 47 33 PM

**Review by NimishaMN — APPROVED** [review]
LGTM

**Review by ShrutiNHegde — APPROVED** [review]

**Comment by zxeleven** [comment]
Verified live:

Screen Shot 2021-08-05 at 4 15 07 PM
Screen Shot 2021-08-05 at 4 15 43 PM
Screen Shot 2021-08-05 at 4 16 53 PM

**Pull request merged**
