### PR TITLE
Clarify the duration of unused offline_access scopes

### PR DESCRIPTION
**Pull request by mbeerman**
Description
----

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

### CODE REVIEW

**Comment by mbeerman** [comment]
The functionality described here is not yet live, but is under development and is expected to roll out this year. The duration is derived from. https://www.healthit.gov/test-method/standardized-api-patient-and-population-services:

> ...a Health IT Module's authorization server must issue a refresh token valid for a period of no less than three months...

**Comment by mbeerman** [comment]
Screen Shot 2021-03-01 at 4 48 13 PM

**Comment by mbeerman** [comment]
Screen Shot 2021-03-01 at 4 51 49 PM

**Review by daliboz — APPROVED** [review]

**Review by MaxPhilips — APPROVED** [review]

**Comment by MaxPhilips** [comment]
live
Screen Shot 2021-03-05 at 12 53 39 PM

**Pull request merged**
